[2023-10-20T10:00:40.641+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=random_cannabis_save/run_id=scheduled__2023-10-19T12:00:00+00:00/task_id=get_random_cannabis permission to 509
[2023-10-20T10:00:40.664+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=random_cannabis_save/run_id=scheduled__2023-10-19T12:00:00+00:00/task_id=get_random_cannabis permission to 509
[2023-10-20T10:00:40.692+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_cannabis_save.get_random_cannabis scheduled__2023-10-19T12:00:00+00:00 [queued]>
[2023-10-20T10:00:40.700+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_cannabis_save.get_random_cannabis scheduled__2023-10-19T12:00:00+00:00 [queued]>
[2023-10-20T10:00:40.701+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-20T10:00:40.716+0000] {taskinstance.py:1382} INFO - Executing <Task(RandomCannabisOperator): get_random_cannabis> on 2023-10-19 12:00:00+00:00
[2023-10-20T10:00:40.723+0000] {standard_task_runner.py:57} INFO - Started process 165 to run task
[2023-10-20T10:00:40.731+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'random_cannabis_save', 'get_random_cannabis', 'scheduled__2023-10-19T12:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/random_cannabis_save.py', '--cfg-path', '/tmp/tmpp0w4l1vo']
[2023-10-20T10:00:40.732+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask get_random_cannabis
[2023-10-20T10:00:40.755+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-10-20T10:00:40.798+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=random_cannabis_save/run_id=scheduled__2023-10-19T12:00:00+00:00/task_id=get_random_cannabis permission to 509
[2023-10-20T10:00:40.800+0000] {task_command.py:416} INFO - Running <TaskInstance: random_cannabis_save.get_random_cannabis scheduled__2023-10-19T12:00:00+00:00 [running]> on host 274b9cde8a7f
[2023-10-20T10:00:40.870+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='babintseva' AIRFLOW_CTX_DAG_ID='random_cannabis_save' AIRFLOW_CTX_TASK_ID='get_random_cannabis' AIRFLOW_CTX_EXECUTION_DATE='2023-10-19T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-19T12:00:00+00:00'
[2023-10-20T10:00:41.470+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/random_cannabis_operator.py", line 32, in execute
    self.save_data(data)
  File "/opt/airflow/plugins/random_cannabis_operator.py", line 22, in save_data
    pg_hook.get_sqlalchemy_engine(),
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 199, in get_sqlalchemy_engine
    return create_engine(self.get_uri(), **engine_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 184, in get_uri
    conn = self.get_connection(getattr(self, self.conn_name_attr))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `conn_greenplum` isn't defined
[2023-10-20T10:00:41.475+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=random_cannabis_save, task_id=get_random_cannabis, execution_date=20231019T120000, start_date=20231020T100040, end_date=20231020T100041
[2023-10-20T10:00:41.485+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task get_random_cannabis (The conn_id `conn_greenplum` isn't defined; 165)
[2023-10-20T10:00:41.505+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-20T10:00:41.524+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
