[2023-10-22T04:38:07.262+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=nhl_stats_save/run_id=manual__2023-10-22T04:38:02.927610+00:00/task_id=save_nhl_stats permission to 509
[2023-10-22T04:38:07.294+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=nhl_stats_save/run_id=manual__2023-10-22T04:38:02.927610+00:00/task_id=save_nhl_stats permission to 509
[2023-10-22T04:38:07.323+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nhl_stats_save.save_nhl_stats manual__2023-10-22T04:38:02.927610+00:00 [queued]>
[2023-10-22T04:38:07.332+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nhl_stats_save.save_nhl_stats manual__2023-10-22T04:38:02.927610+00:00 [queued]>
[2023-10-22T04:38:07.332+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-22T04:38:07.345+0000] {taskinstance.py:1382} INFO - Executing <Task(NhlStatsSaveOperator): save_nhl_stats> on 2023-10-22 04:38:02.927610+00:00
[2023-10-22T04:38:07.359+0000] {standard_task_runner.py:57} INFO - Started process 8037 to run task
[2023-10-22T04:38:07.361+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nhl_stats_save', 'save_nhl_stats', 'manual__2023-10-22T04:38:02.927610+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/nhl_stats_save.py', '--cfg-path', '/tmp/tmphiuuiazg']
[2023-10-22T04:38:07.362+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask save_nhl_stats
[2023-10-22T04:38:07.375+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-10-22T04:38:07.413+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=nhl_stats_save/run_id=manual__2023-10-22T04:38:02.927610+00:00/task_id=save_nhl_stats permission to 509
[2023-10-22T04:38:07.416+0000] {task_command.py:416} INFO - Running <TaskInstance: nhl_stats_save.save_nhl_stats manual__2023-10-22T04:38:02.927610+00:00 [running]> on host 9b9e466d03cf
[2023-10-22T04:38:07.492+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='babintseva' AIRFLOW_CTX_DAG_ID='nhl_stats_save' AIRFLOW_CTX_TASK_ID='save_nhl_stats' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T04:38:02.927610+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T04:38:02.927610+00:00'
[2023-10-22T04:38:08.162+0000] {logging_mixin.py:151} INFO - {'team_uid': 'd35421e2-4622-48d5-836f-48604227cd87', 'uid': '5b40afdb-ca89-4e88-9946-621a6e63656d'}
[2023-10-22T04:38:08.162+0000] {logging_mixin.py:151} INFO - {'displayName': 'statsSingleSeason', 'gameType': {'id': 'R', 'description': 'Regular season', 'postseason': False}}
[2023-10-22T04:38:08.163+0000] {logging_mixin.py:151} INFO - {'team_uid': 'd35421e2-4622-48d5-836f-48604227cd87', 'uid': 'e310a673-4fbe-405e-b605-0a988a02ae41'}
[2023-10-22T04:38:08.163+0000] {logging_mixin.py:151} INFO - {'displayName': 'regularSeasonStatRankings', 'gameType': None}
[2023-10-22T04:38:08.164+0000] {logging_mixin.py:151} INFO - Вставка team:[{'uid': 'd35421e2-4622-48d5-836f-48604227cd87', 'id': 21}]
[2023-10-22T04:38:08.164+0000] {logging_mixin.py:151} INFO - Вставка stats:[{'team_uid': 'd35421e2-4622-48d5-836f-48604227cd87', 'uid': '5b40afdb-ca89-4e88-9946-621a6e63656d', 'displayName': 'statsSingleSeason', 'gameType': {'id': 'R', 'description': 'Regular season', 'postseason': False}}, {'team_uid': 'd35421e2-4622-48d5-836f-48604227cd87', 'uid': 'e310a673-4fbe-405e-b605-0a988a02ae41', 'displayName': 'regularSeasonStatRankings', 'gameType': None}]
[2023-10-22T04:38:08.165+0000] {logging_mixin.py:151} INFO - Вставка splits:[{'stat_uid': '5b40afdb-ca89-4e88-9946-621a6e63656d', 'uid': 'ac95204a-243f-46fa-9a5e-8770faf39319', 'gamesPlayed': 5, 'wins': 5, 'losses': 0, 'ot': 0, 'pts': 10, 'ptPctg': '100.0', 'goalsPerGame': 4.0, 'goalsAgainstPerGame': 1.6, 'evGGARatio': 1.2857, 'powerPlayPercentage': '27.8', 'powerPlayGoals': 5.0, 'powerPlayGoalsAgainst': 1.0, 'powerPlayOpportunities': 18.0, 'penaltyKillPercentage': '95.5', 'shotsPerGame': 37.2, 'shotsAllowed': 28.0, 'winScoreFirst': 1.0, 'winOppScoreFirst': 1.0, 'winLeadFirstPer': 1.0, 'winLeadSecondPer': 1.0, 'winOutshootOpp': 1.0, 'winOutshotByOpp': 1.0, 'faceOffsTaken': 305.0, 'faceOffsWon': 144.0, 'faceOffsLost': 161.0, 'faceOffWinPercentage': '47.2', 'shootingPctg': 10.8, 'savePctg': 0.943}, {'stat_uid': 'e310a673-4fbe-405e-b605-0a988a02ae41', 'uid': '2f009d14-cbba-4941-b904-8e5ca41c2320', 'wins': '2nd', 'losses': '2nd', 'ot': '15th', 'pts': '2nd', 'ptPctg': '2nd', 'goalsPerGame': '6th', 'goalsAgainstPerGame': '2nd', 'evGGARatio': '14th', 'powerPlayPercentage': '9th', 'powerPlayGoals': '9th', 'powerPlayGoalsAgainst': '3rd', 'powerPlayOpportunities': '11th', 'penaltyKillOpportunities': '28th', 'penaltyKillPercentage': '3rd', 'shotsPerGame': '2nd', 'shotsAllowed': '7th', 'winScoreFirst': '6th', 'winOppScoreFirst': '2nd', 'winLeadFirstPer': '8th', 'winLeadSecondPer': '3rd', 'winOutshootOpp': '5th', 'winOutshotByOpp': '5th', 'faceOffsTaken': '10th', 'faceOffsWon': '13th', 'faceOffsLost': '28th', 'faceOffWinPercentage': '24th', 'savePctRank': '2nd', 'shootingPctRank': '11th'}]
[2023-10-22T04:38:08.165+0000] {logging_mixin.py:151} INFO - postgresql+psycopg2://db_homework:db_homework@192.168.1.113:5434/db_homework
[2023-10-22T04:38:08.298+0000] {logging_mixin.py:151} INFO - <class 'dataset.table.Table'>
[2023-10-22T04:38:08.299+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/nhl_stats_save_operator.py", line 86, in execute
    self.save_data(data)
  File "/opt/airflow/plugins/nhl_stats_save_operator.py", line 57, in save_data
    table.insert_many(rows=splits, chunk_size=10000, dtype={"gametype": dialects.postgresql.JSONB})
TypeError: Table.insert_many() got an unexpected keyword argument 'dtype'
[2023-10-22T04:38:08.308+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=nhl_stats_save, task_id=save_nhl_stats, execution_date=20231022T043802, start_date=20231022T043807, end_date=20231022T043808
[2023-10-22T04:38:08.320+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task save_nhl_stats (Table.insert_many() got an unexpected keyword argument 'dtype'; 8037)
[2023-10-22T04:38:08.337+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T04:38:08.356+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
