[2023-10-21T14:05:23.085+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=nhl_stats_save/run_id=manual__2023-10-21T14:05:20.073011+00:00/task_id=save_nhl_stats permission to 509
[2023-10-21T14:05:23.107+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=nhl_stats_save/run_id=manual__2023-10-21T14:05:20.073011+00:00/task_id=save_nhl_stats permission to 509
[2023-10-21T14:05:23.134+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nhl_stats_save.save_nhl_stats manual__2023-10-21T14:05:20.073011+00:00 [queued]>
[2023-10-21T14:05:23.141+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nhl_stats_save.save_nhl_stats manual__2023-10-21T14:05:20.073011+00:00 [queued]>
[2023-10-21T14:05:23.142+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-21T14:05:23.154+0000] {taskinstance.py:1382} INFO - Executing <Task(NhlStatsSaveOperator): save_nhl_stats> on 2023-10-21 14:05:20.073011+00:00
[2023-10-21T14:05:23.160+0000] {standard_task_runner.py:57} INFO - Started process 1686 to run task
[2023-10-21T14:05:23.162+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nhl_stats_save', 'save_nhl_stats', 'manual__2023-10-21T14:05:20.073011+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/nhl_stats_save.py', '--cfg-path', '/tmp/tmp6028qvfn']
[2023-10-21T14:05:23.163+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask save_nhl_stats
[2023-10-21T14:05:23.175+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-10-21T14:05:23.205+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=nhl_stats_save/run_id=manual__2023-10-21T14:05:20.073011+00:00/task_id=save_nhl_stats permission to 509
[2023-10-21T14:05:23.207+0000] {task_command.py:416} INFO - Running <TaskInstance: nhl_stats_save.save_nhl_stats manual__2023-10-21T14:05:20.073011+00:00 [running]> on host f4f5d56d4cc2
[2023-10-21T14:05:23.281+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='babintseva' AIRFLOW_CTX_DAG_ID='nhl_stats_save' AIRFLOW_CTX_TASK_ID='save_nhl_stats' AIRFLOW_CTX_EXECUTION_DATE='2023-10-21T14:05:20.073011+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-21T14:05:20.073011+00:00'
[2023-10-21T14:05:24.004+0000] {logging_mixin.py:151} INFO - {'team_uid': '7736c0e5-b922-44db-a492-0e5dd93ceabc', 'uid': 'ee149fe2-9557-4225-82ee-163cbca6eda9'}
[2023-10-21T14:05:24.005+0000] {logging_mixin.py:151} INFO - {'displayName': 'statsSingleSeason', 'gameType': {'id': 'R', 'description': 'Regular season', 'postseason': False}}
[2023-10-21T14:05:24.005+0000] {logging_mixin.py:151} INFO - {'team_uid': '7736c0e5-b922-44db-a492-0e5dd93ceabc', 'uid': '388f8bcb-9f2e-4df3-8dfd-2f836a7c52be'}
[2023-10-21T14:05:24.006+0000] {logging_mixin.py:151} INFO - {'displayName': 'regularSeasonStatRankings', 'gameType': None}
[2023-10-21T14:05:24.006+0000] {logging_mixin.py:151} INFO - Вставка team:[{'uid': '7736c0e5-b922-44db-a492-0e5dd93ceabc', 'id': 21}]
[2023-10-21T14:05:24.007+0000] {logging_mixin.py:151} INFO - Вставка stats:[{'team_uid': '7736c0e5-b922-44db-a492-0e5dd93ceabc', 'uid': 'ee149fe2-9557-4225-82ee-163cbca6eda9', 'displayName': 'statsSingleSeason', 'gameType': {'id': 'R', 'description': 'Regular season', 'postseason': False}}, {'team_uid': '7736c0e5-b922-44db-a492-0e5dd93ceabc', 'uid': '388f8bcb-9f2e-4df3-8dfd-2f836a7c52be', 'displayName': 'regularSeasonStatRankings', 'gameType': None}]
[2023-10-21T14:05:24.007+0000] {logging_mixin.py:151} INFO - Вставка splits:[{'stat_uid': 'ee149fe2-9557-4225-82ee-163cbca6eda9', 'uid': 'f69357e3-1a88-4e1c-9305-b5d091912194', 'gamesPlayed': 4, 'wins': 4, 'losses': 0, 'ot': 0, 'pts': 8, 'ptPctg': '100.0', 'goalsPerGame': 3.5, 'goalsAgainstPerGame': 1.0, 'evGGARatio': 1.75, 'powerPlayPercentage': '15.4', 'powerPlayGoals': 2.0, 'powerPlayGoalsAgainst': 0.0, 'powerPlayOpportunities': 13.0, 'penaltyKillPercentage': '100.0', 'shotsPerGame': 39.5, 'shotsAllowed': 28.25, 'winScoreFirst': 1.0, 'winOppScoreFirst': 1.0, 'winLeadFirstPer': 1.0, 'winLeadSecondPer': 1.0, 'winOutshootOpp': 1.0, 'winOutshotByOpp': 1.0, 'faceOffsTaken': 243.0, 'faceOffsWon': 112.0, 'faceOffsLost': 131.0, 'faceOffWinPercentage': '46.1', 'shootingPctg': 8.9, 'savePctg': 0.965}, {'stat_uid': '388f8bcb-9f2e-4df3-8dfd-2f836a7c52be', 'uid': '0fe14afb-3aaf-4231-b17b-d09971692541', 'wins': '2nd', 'losses': '2nd', 'ot': '12th', 'pts': '2nd', 'ptPctg': '2nd', 'goalsPerGame': '8th', 'goalsAgainstPerGame': '1st', 'evGGARatio': '6th', 'powerPlayPercentage': '21st', 'powerPlayGoals': '18th', 'powerPlayGoalsAgainst': '1st', 'powerPlayOpportunities': '20th', 'penaltyKillOpportunities': '23rd', 'penaltyKillPercentage': '1st', 'shotsPerGame': '1st', 'shotsAllowed': '10th', 'winScoreFirst': '4th', 'winOppScoreFirst': '2nd', 'winLeadFirstPer': '8th', 'winLeadSecondPer': '4th', 'winOutshootOpp': '7th', 'winOutshotByOpp': '7th', 'faceOffsTaken': '16th', 'faceOffsWon': '21st', 'faceOffsLost': '23rd', 'faceOffWinPercentage': '27th', 'savePctRank': '1st', 'shootingPctRank': '19th'}]
[2023-10-21T14:05:24.056+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InsufficientPrivilege: permission denied for table team


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/airflow/plugins/nhl_stats_save_operator.py", line 84, in execute
    self.save_data(data)
  File "/opt/airflow/plugins/nhl_stats_save_operator.py", line 51, in save_data
    table.insert_many(rows=team, chunk_size=10000)
  File "/home/airflow/.local/lib/python3.10/site-packages/dataset/table.py", line 184, in insert_many
    self.table.insert().execute(chunk)
  File "<string>", line 2, in execute
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 468, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 965, in execute
    return e._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InsufficientPrivilege) permission denied for table team

[SQL: INSERT INTO team (uid, id) VALUES (%(uid)s, %(id)s)]
[parameters: {'uid': UUID('7736c0e5-b922-44db-a492-0e5dd93ceabc'), 'id': 21}]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2023-10-21T14:05:24.065+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=nhl_stats_save, task_id=save_nhl_stats, execution_date=20231021T140520, start_date=20231021T140523, end_date=20231021T140524
[2023-10-21T14:05:24.075+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 15 for task save_nhl_stats ((psycopg2.errors.InsufficientPrivilege) permission denied for table team

[SQL: INSERT INTO team (uid, id) VALUES (%(uid)s, %(id)s)]
[parameters: {'uid': UUID('7736c0e5-b922-44db-a492-0e5dd93ceabc'), 'id': 21}]
(Background on this error at: https://sqlalche.me/e/14/f405); 1686)
[2023-10-21T14:05:24.097+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-21T14:05:24.115+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
