[2023-10-22T06:21:51.876+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=nhl_stats_save/run_id=manual__2023-10-22T06:21:50.018659+00:00/task_id=save_nhl_stats permission to 509
[2023-10-22T06:21:51.898+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=nhl_stats_save/run_id=manual__2023-10-22T06:21:50.018659+00:00/task_id=save_nhl_stats permission to 509
[2023-10-22T06:21:51.920+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nhl_stats_save.save_nhl_stats manual__2023-10-22T06:21:50.018659+00:00 [queued]>
[2023-10-22T06:21:51.927+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nhl_stats_save.save_nhl_stats manual__2023-10-22T06:21:50.018659+00:00 [queued]>
[2023-10-22T06:21:51.928+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-22T06:21:51.939+0000] {taskinstance.py:1382} INFO - Executing <Task(NhlStatsSaveOperator): save_nhl_stats> on 2023-10-22 06:21:50.018659+00:00
[2023-10-22T06:21:51.945+0000] {standard_task_runner.py:57} INFO - Started process 1324 to run task
[2023-10-22T06:21:51.947+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nhl_stats_save', 'save_nhl_stats', 'manual__2023-10-22T06:21:50.018659+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/nhl_stats_save.py', '--cfg-path', '/tmp/tmp4lx6dcv5']
[2023-10-22T06:21:51.949+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask save_nhl_stats
[2023-10-22T06:21:51.959+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-10-22T06:21:51.984+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=nhl_stats_save/run_id=manual__2023-10-22T06:21:50.018659+00:00/task_id=save_nhl_stats permission to 509
[2023-10-22T06:21:51.986+0000] {task_command.py:416} INFO - Running <TaskInstance: nhl_stats_save.save_nhl_stats manual__2023-10-22T06:21:50.018659+00:00 [running]> on host 06f8d34233ae
[2023-10-22T06:21:52.044+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='babintseva' AIRFLOW_CTX_DAG_ID='nhl_stats_save' AIRFLOW_CTX_TASK_ID='save_nhl_stats' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T06:21:50.018659+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T06:21:50.018659+00:00'
[2023-10-22T06:21:52.723+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/nhl_stats_save_operator.py", line 101, in execute
    self.save_data(data)
  File "/opt/airflow/plugins/nhl_stats_save_operator.py", line 74, in save_data
    (team, stats, splits) = self.parse_data(df)
  File "/opt/airflow/plugins/nhl_stats_save_operator.py", line 66, in parse_data
    'save_pct_rank': jsSplit.get('stat')['savePctRank'],
KeyError: 'savePctRank'
[2023-10-22T06:21:52.731+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=nhl_stats_save, task_id=save_nhl_stats, execution_date=20231022T062150, start_date=20231022T062151, end_date=20231022T062152
[2023-10-22T06:21:52.743+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task save_nhl_stats ('savePctRank'; 1324)
[2023-10-22T06:21:52.761+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T06:21:52.778+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
