[2023-10-20T12:18:50.816+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=nhl_stats_save/run_id=manual__2023-10-20T12:18:48.441594+00:00/task_id=save_nhl_stats permission to 509
[2023-10-20T12:18:50.842+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=nhl_stats_save/run_id=manual__2023-10-20T12:18:48.441594+00:00/task_id=save_nhl_stats permission to 509
[2023-10-20T12:18:50.866+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nhl_stats_save.save_nhl_stats manual__2023-10-20T12:18:48.441594+00:00 [queued]>
[2023-10-20T12:18:50.872+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nhl_stats_save.save_nhl_stats manual__2023-10-20T12:18:48.441594+00:00 [queued]>
[2023-10-20T12:18:50.873+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-20T12:18:50.884+0000] {taskinstance.py:1382} INFO - Executing <Task(NhlStatsSaveOperator): save_nhl_stats> on 2023-10-20 12:18:48.441594+00:00
[2023-10-20T12:18:50.890+0000] {standard_task_runner.py:57} INFO - Started process 90 to run task
[2023-10-20T12:18:50.892+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nhl_stats_save', 'save_nhl_stats', 'manual__2023-10-20T12:18:48.441594+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/nhl_stats_save.py', '--cfg-path', '/tmp/tmp01i4m_m7']
[2023-10-20T12:18:50.893+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask save_nhl_stats
[2023-10-20T12:18:50.904+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-10-20T12:18:50.930+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=nhl_stats_save/run_id=manual__2023-10-20T12:18:48.441594+00:00/task_id=save_nhl_stats permission to 509
[2023-10-20T12:18:50.933+0000] {task_command.py:416} INFO - Running <TaskInstance: nhl_stats_save.save_nhl_stats manual__2023-10-20T12:18:48.441594+00:00 [running]> on host 8508280b5a6b
[2023-10-20T12:18:50.989+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='babintseva' AIRFLOW_CTX_DAG_ID='nhl_stats_save' AIRFLOW_CTX_TASK_ID='save_nhl_stats' AIRFLOW_CTX_EXECUTION_DATE='2023-10-20T12:18:48.441594+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-20T12:18:48.441594+00:00'
[2023-10-20T12:18:51.506+0000] {logging_mixin.py:151} INFO - {'team_uid': UUID('394ea220-6fbd-4dd2-8578-85d4d1e4621a'), 'uid': UUID('f28ed868-7b01-497c-a306-109b9eb76cab'), 'load_date': datetime.datetime(2023, 10, 20, 12, 18, 51, 506345)}
[2023-10-20T12:18:51.507+0000] {logging_mixin.py:151} INFO - {'displayName': 'statsSingleSeason', 'gameType': {'id': 'R', 'description': 'Regular season', 'postseason': False}}
[2023-10-20T12:18:51.507+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/nhl_stats_save_operator.py", line 69, in execute
    self.save_data(data)
  File "/opt/airflow/plugins/nhl_stats_save_operator.py", line 40, in save_data
    (team, stats, splits) = self.parse_data(df)
  File "/opt/airflow/plugins/nhl_stats_save_operator.py", line 31, in parse_data
    stat = {'team_uid': team_uid, 'uid': stat_uid, 'load_date': load_date} | jsStat.get('type')
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
[2023-10-20T12:18:51.516+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=nhl_stats_save, task_id=save_nhl_stats, execution_date=20231020T121848, start_date=20231020T121850, end_date=20231020T121851
[2023-10-20T12:18:51.527+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 18 for task save_nhl_stats (unsupported operand type(s) for |: 'dict' and 'dict'; 90)
[2023-10-20T12:18:51.547+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-20T12:18:51.566+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
